//
// Module CatRecognizer2020_lib.async_reset_sync
//
// Created:
//          by - eshelga.UNKNOWN (L118W111)
//          at - 23:15:06 12/26/2019
//
// Generated by Mentor Graphics HDL Designer(TM) 2019.2 (Build 5)
//

`resetall
`timescale 1ns/10ps
module async_resetFFstyle2 (
  input  wire   clk,   //clk
  input wire    rst_async, // non synchrnized reset
  output reg    rst //synchyronized reset
  );

  reg rff1;                                   //synchrnization flip flop
  // testing 123
  always @(posedge clk or negedge rst_async)  //main proce
  begin :sync_proc 
    if (!rst_async) //reset 
      {rst,rff1} <= 2'b0;  //reset the ff
    else 
      {rst,rff1} <= {rff1,1'b1}; //set the ff
  end
endmodule
