//
// Module CatRecognizer2020_lib.CatRecognizerFast.struct
//
// Created:
//          by - eldadha.UNKNOWN (L118W111)
//          at - 11:59:58 01/10/2020
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//

`resetall
`timescale 1ns/10ps
`include "params.v"
module CatRecognizerFast( 
   // Port Declarations
   input   wire                            clk,        // clock
   input   wire    [`AMBA_ADDR_DEPTH-1:0]  paddr,      // address
   input   wire                            penable,    // enable
   input   wire                            psel,       // select
   input   wire    [`AMBA_WORD - 1:0]      pwdata,     // write data
   input   wire                            pwrite,     // write data
   input   wire                            rst_async,  // reset async
   output  wire                            calc_done,  // finish calc
   output  wire                            catrecout,  // output
   output  wire    [`AMBA_WORD - 1:0]      prdata,     //  read data
   output  wire                            pready      // ready to transfer
);


// Internal Declarations


// Local declarations

// Internal signal declarations
wire        [`WEIGHT_BIAS_PRECISION-`ONE_bit:0]                   bias;         // APB
wire                                                              mac_done;     //MAC output is valid
wire signed [`PIXEL_PRECISION+`WEIGHT_BIAS_PRECISION+1:0]         mac_out;      //output
wire                                                              over_flow;    //overflow at one of the adders
wire        [`PIXEL_PRECISION*`NUMBER_OF_PIXELS-`ONE_bit:0]       pixdata;      // APB
wire                                                              rst;
wire                                                              start_work;   // APB
wire        [`WEIGHT_BIAS_PRECISION*`NUMBER_OF_PIXELS-`ONE_bit:0] weights;      // APB


// Instances 
APB U_0( 
   .clk        (clk), 
   .paddr      (paddr), 
   .penable    (penable), 
   .psel       (psel), 
   .pwdata     (pwdata), 
   .pwrite     (pwrite), 
   .calc_done  (calc_done), 
   .rst        (rst), 
   .bias       (bias), 
   .pixdata    (pixdata), 
   .prdata     (prdata), 
   .pready     (pready), 
   .start_work (start_work), 
   .weights    (weights)
); 

MAC U_1( 
   .clk        (clk), 
   .rst        (rst), 
   .start_work (start_work), 
   .bias       (bias), 
   .pixdata    (pixdata), 
   .weights    (weights), 
   .mac_done   (mac_done), 
   .mac_out    (mac_out), 
   .over_flow  (over_flow)
); 

async_resetFFstyle2 U_3( 
   .clk       (clk), 
   .rst_async (rst_async), 
   .rst       (rst)
); 

sign U_2( 
   .clk       (clk), 
   .rst       (rst), 
   .z         (mac_out), 
   .over_flow (over_flow), 
   .mac_done  (mac_done), 
   .catrecout (catrecout), 
   .calc_done (calc_done)
); 


endmodule // CatRecognizerFast

