//
// Module CatRecognizer2020_lib.sign
//
// Created:
//          by - eshelga.UNKNOWN (L330W509)
//          at - 20:34:22 11/27/2019
//
// Generated by Mentor Graphics HDL Designer(TM) 2019.2 (Build 5)
//

`resetall
`timescale 1ns/10ps
`include "params.v"
`define zero 0
module sign( 
  // Port Declarations
  input   wire clk,         //clock
  input   wire rst,         //reset
  input   wire  signed  [`PIXEL_PRECISION+`WEIGHT_BIAS_PRECISION+1:0]  z,  //The sigmoind input z
  input   wire  over_flow,                                                        //overflow at one of the adders
  input   wire mac_done,                                                          //MAC output is valid
  output  reg  catrecout,                                                         //cat recognition output - 1 is a cat, 0 is not a cat
  output  reg  calc_done                                                          //cat output is valid 
  );
  
  
  // eb1 1
  always@(
  posedge clk,
  negedge rst)
  begin: Sigmoind_proc
    if (!rst) //initialize the registers 
    begin
      catrecout <= 0;   //initialize the registers 
      calc_done <= 0;   //initialize the registers 
    end
    else
    begin
      if (mac_done)   //the MAC output is valid
      begin
        calc_done <= 1;   //the cat recognizer finished its calculation
        if (z > `zero && !over_flow)      //Translation from the sigmoind function to a simpler condition
        begin
          catrecout <= 1;           //it is a cat!
        end
      end
      else
      begin
        catrecout <= 0;           //not valid output
        calc_done <= 0;           //not valid output
      end
    end
  end
  
endmodule